// ─── Model Coefficients (from trained Logistic Regression) ───────────────────
// Real coefficients trained on the Wisconsin Breast Cancer dataset
// Logistic Regression — ROC-AUC: 0.9950 | Accuracy: 95.0%
// Generated by: python src/train.py

const MODEL = {
  // Real Logistic Regression weights (StandardScaler normalized)
  // Features: clump_thickness, size_uniformity, shape_uniformity, marginal_adhesion,
  //           epithelial_size, bare_nucleoli, bland_chromatin, normal_nucleoli, mitoses
  coef: [1.1839083042675373, 0.12168528350008959, 0.759275097769862,
         0.5764310626201111, 0.18373781732581942, 1.6377139544276214,
         0.8763432352468541, 0.5630434290411908, 0.7900398606073157],
  intercept: -1.153080361588838,
  // Real StandardScaler params from training data (n=559 samples)
  scaler_mean: [4.459749552772808, 3.1556350626118066, 3.230769230769231,
                2.8246869409660107, 3.216457960644007, 3.524150268336315,
                3.452593917710197, 2.8747763864042932, 1.6529516994633273],
  scaler_scale: [2.82553028725253, 3.0963824901228096, 2.9767226846615813,
                 2.9035846453772547, 2.2053799021917304, 3.6392375627653464,
                 2.4416238983220624, 3.062624345852325, 1.8146061286021424],
  features: [
    'clump_thickness', 'size_uniformity', 'shape_uniformity', 'marginal_adhesion',
    'epithelial_size', 'bare_nucleoli', 'bland_chromatin', 'normal_nucleoli', 'mitoses'
  ],
  // Feature importance from LR coefficients (absolute normalized)
  importance: [0.1839, 0.0189, 0.1180, 0.0896, 0.0286, 0.2546, 0.1363, 0.0875, 0.1228],
  best_model: 'Logistic Regression',
  best_accuracy: 0.9500,
  best_roc_auc: 0.9950
};

// Load real coefficients if available
fetch('../models/model_coefficients.json')
  .then(r => r.json())
  .then(data => {
    Object.assign(MODEL, data);
    console.log('✅ Loaded real model coefficients');
  })
  .catch(() => console.log('ℹ️ Using embedded model coefficients'));

// ─── Feature Definitions ──────────────────────────────────────────────────────
const FEATURES = [
  { key: 'clump_thickness',    label: 'Clump Thickness',     desc: 'Thickness of cell clumps (1=thin, 10=thick)' },
  { key: 'size_uniformity',    label: 'Cell Size Uniformity', desc: 'Uniformity in cell size (1=uniform, 10=varied)' },
  { key: 'shape_uniformity',   label: 'Cell Shape Uniformity',desc: 'Uniformity of cell shapes (1=uniform, 10=varied)' },
  { key: 'marginal_adhesion',  label: 'Marginal Adhesion',    desc: 'Cell clumping tendency (1=low, 10=high)' },
  { key: 'epithelial_size',    label: 'Epithelial Cell Size', desc: 'Epithelial cell size relative to normal' },
  { key: 'bare_nucleoli',      label: 'Bare Nucleoli',        desc: 'Nuclei without cytoplasm (1=few, 10=many)' },
  { key: 'bland_chromatin',    label: 'Bland Chromatin',      desc: 'Chromatin texture uniformity' },
  { key: 'normal_nucleoli',    label: 'Normal Nucleoli',      desc: 'Nucleoli size and visibility' },
  { key: 'mitoses',            label: 'Mitoses',              desc: 'Cell division activity (1=rare, 10=frequent)' },
];

// ─── State ─────────────────────────────────────────────────────────────────────
const state = { values: {} };
FEATURES.forEach(f => { state.values[f.key] = 1; });

// ─── Initialize UI ─────────────────────────────────────────────────────────────
function init() {
  renderFeatureSliders();
  renderImportanceBars();
}

function getBadgeClass(val) {
  if (val <= 3) return 'badge-low';
  if (val <= 6) return 'badge-mid';
  return 'badge-high';
}

function renderFeatureSliders() {
  const grid = document.getElementById('featuresGrid');
  grid.innerHTML = '';
  FEATURES.forEach((feat, idx) => {
    const val = state.values[feat.key];
    const pct = ((val - 1) / 9) * 100;
    const div = document.createElement('div');
    div.className = 'slider-item';
    div.innerHTML = `
      <div class="slider-label-row">
        <span class="slider-label">${feat.label}</span>
        <span class="slider-badge ${getBadgeClass(val)}" id="badge-${feat.key}">${val}</span>
      </div>
      <input
        type="range" min="1" max="10" step="1" value="${val}"
        class="feature-slider"
        id="slider-${feat.key}"
        style="--pct: ${pct}%"
        oninput="onSliderChange('${feat.key}', this.value)"
        aria-label="${feat.label}"
      />
      <span class="slider-desc">${feat.desc}</span>
    `;
    grid.appendChild(div);
  });
}

function onSliderChange(key, rawVal) {
  const val = parseInt(rawVal);
  state.values[key] = val;
  const badge = document.getElementById(`badge-${key}`);
  const slider = document.getElementById(`slider-${key}`);
  badge.textContent = val;
  badge.className = `slider-badge ${getBadgeClass(val)}`;
  const pct = ((val - 1) / 9) * 100;
  slider.style.setProperty('--pct', pct + '%');
}

// ─── Sigmoid ───────────────────────────────────────────────────────────────────
function sigmoid(z) {
  return 1 / (1 + Math.exp(-z));
}

// ─── Predict ───────────────────────────────────────────────────────────────────
function predict() {
  // Scale features using training scaler params
  const scaled = MODEL.features.map((feat, i) => {
    return (state.values[feat] - MODEL.scaler_mean[i]) / MODEL.scaler_scale[i];
  });

  // Compute logit
  let logit = MODEL.intercept;
  MODEL.coef.forEach((c, i) => { logit += c * scaled[i]; });
  const probMalignant = sigmoid(logit);
  const probBenign = 1 - probMalignant;
  const isMalignant = probMalignant >= 0.5;
  const confidence = isMalignant ? probMalignant : probBenign;

  showResult(isMalignant, confidence, probMalignant);
}

// ─── Show Result ───────────────────────────────────────────────────────────────
function showResult(isMalignant, confidence, probMalignant) {
  const card = document.getElementById('resultCard');
  const placeholder = document.getElementById('resultPlaceholder');
  const content = document.getElementById('resultContent');
  const icon = document.getElementById('resultIcon');
  const title = document.getElementById('resultTitle');
  const confVal = document.getElementById('confidenceValue');
  const confFill = document.getElementById('confidenceFill');
  const summary = document.getElementById('featureSummary');
  const gaugeLabel = document.getElementById('gaugeLabel');

  placeholder.style.display = 'none';
  content.style.display = 'block';

  // Reset class
  card.classList.remove('result-benign', 'result-malignant');
  card.classList.add(isMalignant ? 'result-malignant' : 'result-benign');

  if (isMalignant) {
    icon.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="28" height="28" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>`;
    title.innerHTML = `Malignant<small>High-risk — Please consult a physician</small>`;
  } else {
    icon.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="28" height="28" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>`;
    title.innerHTML = `Benign<small>Low-risk — Likely non-cancerous</small>`;
  }

  const pct = Math.round(confidence * 100);
  confVal.textContent = `${pct}%`;
  confFill.style.width = `${pct}%`;

  gaugeLabel.textContent = `Malignancy Probability: ${Math.round(probMalignant * 100)}%`;
  drawGauge(probMalignant);

  // Feature tags
  summary.innerHTML = '';
  FEATURES.forEach(f => {
    const val = state.values[f.key];
    const tag = document.createElement('span');
    tag.className = 'feature-tag';
    const isHigh = val >= 7;
    const isMid = val >= 4;
    tag.style.cssText = `
      background: ${isHigh ? '#F5ECE7' : isMid ? '#FFFFE3' : '#EDF1EC'};
      color: ${isHigh ? '#A8664F' : isMid ? '#6D8196' : '#6E8B7A'};
      border-color: ${isHigh ? '#EAD9CE' : isMid ? '#CBCBCB' : '#DCE5DE'};
    `;
    tag.textContent = `${f.label}: ${val}`;
    summary.appendChild(tag);
  });

  // Smooth scroll to result
  document.getElementById('resultCard').scrollIntoView({ behavior: 'smooth', block: 'center' });
}

// ─── Gauge Canvas ──────────────────────────────────────────────────────────────
function drawGauge(prob) {
  const canvas = document.getElementById('gaugeCanvas');
  const ctx = canvas.getContext('2d');
  const W = canvas.width, H = canvas.height;
  ctx.clearRect(0, 0, W, H);

  const cx = W / 2, cy = H - 10;
  const r = Math.min(W, H * 2) / 2 - 12;
  const startAngle = Math.PI;
  const endAngle = 2 * Math.PI;

  // Background arc
  ctx.beginPath();
  ctx.arc(cx, cy, r, startAngle, endAngle);
  ctx.lineWidth = 14;
  ctx.strokeStyle = '#CBCBCB';
  ctx.lineCap = 'round';
  ctx.stroke();

  // Color gradient arc
  const gradient = ctx.createLinearGradient(cx - r, cy, cx + r, cy);
  gradient.addColorStop(0, '#6E8B7A');
  gradient.addColorStop(0.5, '#6D8196');
  gradient.addColorStop(1, '#A8664F');

  const fillAngle = startAngle + prob * Math.PI;
  ctx.beginPath();
  ctx.arc(cx, cy, r, startAngle, fillAngle);
  ctx.strokeStyle = gradient;
  ctx.lineWidth = 14;
  ctx.lineCap = 'round';
  ctx.stroke();

  // Needle
  const needleAngle = startAngle + prob * Math.PI;
  const nx = cx + (r - 8) * Math.cos(needleAngle);
  const ny = cy + (r - 8) * Math.sin(needleAngle);
  ctx.beginPath();
  ctx.moveTo(cx, cy);
  ctx.lineTo(nx, ny);
  ctx.lineWidth = 3;
  ctx.strokeStyle = '#4A4A4A';
  ctx.lineCap = 'round';
  ctx.stroke();

  // Needle circle
  ctx.beginPath();
  ctx.arc(cx, cy, 6, 0, 2 * Math.PI);
  ctx.fillStyle = '#4A4A4A';
  ctx.fill();

  // Labels
  ctx.font = '500 10px Inter, sans-serif';
  ctx.fillStyle = '#7A7A7A';
  ctx.textAlign = 'center';
  ctx.fillText('Benign', cx - r + 8, cy - 4);
  ctx.fillText('Malignant', cx + r - 8, cy - 4);
}

// ─── Feature Importance Bars ───────────────────────────────────────────────────
function renderImportanceBars() {
  const container = document.getElementById('importanceBars');
  const maxImp = Math.max(...MODEL.importance);
  const colors = ['#6D8196', '#7A8DA0', '#879AAA', '#94A6B4', '#A1B2BE', '#AEBEC8', '#BBCAD2', '#C8D6DC', '#4A4A4A'];

  const sorted = FEATURES.map((f, i) => ({ ...f, imp: MODEL.importance[i] }))
    .sort((a, b) => b.imp - a.imp);

  container.innerHTML = sorted.map((f, i) => {
    const pct = Math.round((f.imp / maxImp) * 100);
    return `
      <div class="imp-bar-row">
        <span class="imp-label">${f.label}</span>
        <div class="imp-bar-track">
          <div class="imp-bar-fill" style="width:${pct}%; background:${colors[i]};"></div>
        </div>
        <span class="imp-pct">${(f.imp * 100).toFixed(1)}%</span>
      </div>
    `;
  }).join('');
}

// ─── Reset ─────────────────────────────────────────────────────────────────────
function resetForm() {
  FEATURES.forEach(f => { state.values[f.key] = 1; });
  renderFeatureSliders();

  const placeholder = document.getElementById('resultPlaceholder');
  const content = document.getElementById('resultContent');
  const card = document.getElementById('resultCard');
  placeholder.style.display = 'flex';
  content.style.display = 'none';
  card.classList.remove('result-benign', 'result-malignant');
}

// ─── Run ───────────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', init);
